# Generated by Django 4.1.3 on 2022-11-22 15:15

import django.core.validators
from django.db import migrations, models
import repayment_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(1000)])),
                ('loan_term', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateField(validators=[repayment_api.models.Loan.validate_date])),
                ('updated_at', models.DateField(blank=True)),
            ],
        ),
    ]
