# Generated by Django 4.1.3 on 2022-11-22 07:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repaymentprofile',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='repaymentprofile',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='repaymentprofile',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='repaymentprofile',
            name='term',
        ),
        migrations.AddField(
            model_name='repaymentprofile',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentprofile',
            name='loan_amount',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentprofile',
            name='loan_term',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaymentprofile',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
