# Generated by Django 4.1.3 on 2022-11-23 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='updated_at',
            field=models.DateField(default=datetime.date(2022, 11, 23)),
        ),
    ]
