# Generated by Django 4.1.3 on 2022-11-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_month',
            field=models.IntegerField(),
        ),
    ]
