# Generated by Django 4.1.3 on 2022-11-24 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_api', '0004_repaymentschedule_alter_loan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=6, max_digits=21, validators=[django.core.validators.MaxValueValidator(100000000), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
