# Generated by Django 4.1.3 on 2022-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_api', '0006_alter_repaymentschedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaymentschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
